## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [1]:
import pandas as pd

In [2]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [3]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [4]:
data[data['sex'] == 'Male']['age'].mean()

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [8]:
(data['native-country'] == 'United-States').sum() / len(data)

np.float64(0.895857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [ ]:
data['salary'].value_counts() #для понимания значений этого поля

salary
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [17]:
z4_1 = data[data['salary'] == '>50K']['age'].mean()
z4_2 = data[data['salary'] == '>50K']['age'].std()

z5_1 = data[data['salary'] == '<=50K']['age'].mean()
z5_2 = data[data['salary'] == '<=50K']['age'].std()

print("Зп >50K:")
print(f"Средний возраст {z4_1:.2f}")
print(f"Стандартное отклонение {z4_2:.2f}")

print("\nЗп <=50K:")
print(f"Средний возраст {z5_1:.2f}")
print(f"Стандартное отклонение {z5_2:.2f}")

Зп >50K:
Средний возраст 44.25
Стандартное отклонение 10.52

Зп <=50K:
Средний возраст 36.78
Стандартное отклонение 14.02

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [21]:
data['education'].unique() #для понимания значений этого поля

<ArrowStringArray>
[   'Bachelors',      'HS-grad',         '11th',      'Masters',
          '9th', 'Some-college',   'Assoc-acdm',    'Assoc-voc',
      '7th-8th',    'Doctorate',  'Prof-school',      '5th-6th',
         '10th',      '1st-4th',    'Preschool',         '12th']
Length: 16, dtype: str

In [26]:
arr_ed = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
data[data['salary'] == '>50K']['education'].isin(arr_ed).value_counts()

education
True     4535
False    3306
Name: count, dtype: int64

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

### *Мой ответ 90, что видно из таблицы*

In [27]:
data.groupby(['race', 'sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [43]:
mask_z8 = data['marital-status'].str.startswith('Married')
married_z8= data[mask_z8]
single_z8= data[~mask_z8]

z8_1= len(married_z8[married_z8['salary'] == '>50K']) / len(married_z8)
z8_2= len(single_z8[single_z8['salary'] == '>50K']) / len(single_z8)

print(f"Доля зарабатывающих >50K среди женатых {z8_1 * 100:.2f}%")
print(f"Доля зарабатывающих >50K среди холостых {z8_2 * 100:.2f}%")

Доля зарабатывающих >50K среди женатых 43.69%
Доля зарабатывающих >50K среди холостых 6.45%

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [51]:
max_h = data['hours-per-week'].max()
count_m = len(data[data['hours-per-week'] == max_h])
sal_c_m= len(data[(data['hours-per-week'] == max_h) & (data['salary'] == '>50K')]) / count_m

print(f"Макс количество часов в неделю {max_h}")
print(f"Столько часов работают {count_m} человек")
print(f"Из них зарабатывают >50K {sal_c_m *100:.2f}%")

Макс количество часов в неделю 99
Столько часов работают 85 человек
Из них зарабатывают >50K 29.41%

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [70]:
data.groupby(['salary', 'native-country'])['hours-per-week'].mean().round(2).sort_values(ascending=False)

salary  native-country
>50K    Honduras          60.00
        Thailand          58.33
        South             51.44
        France            50.75
        Greece            50.62
                          ...
<=50K   El-Salvador       36.03
        Peru              35.07
        Honduras          34.33
        Taiwan            33.77
        Hungary           31.30
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [71]:
data['AgeGroup'] = pd.cut(data['age'], [16, 35, 70, 100], labels=["young", "adult", "retiree"])

In [75]:
data[['age', 'AgeGroup']].head(10)

   age AgeGroup
0   39    adult
1   50    adult
2   38    adult
3   53    adult
4   28    young
5   37    adult
6   49    adult
7   52    adult
8   31    young
9   42    adult

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [86]:
z12 = data[data['salary'] == '>50K'].groupby('AgeGroup').size()

print(f"Количество зарабатывающих >50K в каждой из возрастных групп: {z12}")
print(f"Название возрастной группы, в которой чаще зарабатывают >50K: {z12.idxmax()}")

Количество зарабатывающих >50K в каждой из возрастных групп: AgeGroup
young      1705
adult      6042
retiree      94
dtype: int64
Название возрастной группы, в которой чаще зарабатывают >50K: adult

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [102]:
z14 = data.groupby('occupation').size()
print(f"Количество людей по типу занятости {z14}")

def filter_func(g):
    if g['age'].mean() <= 40 and g['hours-per-week'].min() > 5:
        return True
    else:
        return False

z14_1 = data.groupby('occupation').filter(filter_func)['occupation'].unique()
print(f"\nФильтрация\n{z14_1}")

Количество людей по типу занятости occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

Фильтрация
<ArrowStringArray>
['Armed-Forces']
Length: 1, dtype: str